### ISSUE TITLE
escape ampersands?

### ISSUE THREAD

**Issue by edsu** [gsf/whiskers.js#25]
Has escaping things like & come up before? For example:

```
> w.render('<title>{title}</title>', {title: 'foo & bar'})
'<title>foo & bar</title>'
```

should do this instead?

```
> w.render('<title>{title}</title>', {title: 'foo & bar'})
'<title>foo &amp; bar</title>'
```

**Comment by Malvineous** [comment]
Is this still the case?  I am passing large JSON objects from someone else's API to some templates, so need to escape every single object property before it ends up in the HTML.  It would be a pain to iterate through the whole object however deep it is and escape every single property, especially when I'm not using all the fields anyway.

Would adding HTML escaping in Whiskers be a simple thing to do?

On a related note, I can't find any documentation about what the `>` operator does.  Given the README uses `{>header}` for the only object property in the example containing raw HTML, I presumed this was how you told Whiskers NOT to escape that field, and everything else was escaped, but alas there appears to be no change, escaping or otherwise, when I use this prefix!  So I'm not sure what it's for.  But it *would* be a good way of marking a given field that shouldn't be escaped.
